------------------------------
NGIX.YAML

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: cloudacademy
data:
  nginx.conf: |-
    #CODE1.0:
    #add the nginx.conf configuration - this will be referenced within the deployment.yaml
 #add the nginx.conf configuration - this will be referenced within the deployment.yaml
 server {
 listen 80;
 server_name localhost;
location / {
   proxy_pass http://localhost:5000/;
   proxy_set_header Host "localhost";
 }
}

#CODE2.0:
#add the NGINX container to the pod - configure it to mount the nginx.conf file stored in the nginx-conf configMap 
- name: nginx
  image: nginx:1.13.7
  imagePullPolicy: IfNotPresent
  ports:
  - name: http
    containerPort: 80
  volumeMounts:
  - name: nginx-proxy-config
    mountPath: /etc/nginx/conf.d/default.conf
    subPath: nginx.conf

#CODE2.1:
#add the FLASK container to the pod
- name: flask
  image: cloudacademydevops/flaskapp
  imagePullPolicy: IfNotPresent
  ports:
  - name: http
    containerPort: 5000
  env:
  - name: APP_NAME
    value: CloudAcademy.DevOps.K8s.Manifest
#CODE2.2:
#reference the nginx-conf configMap - this will be mounted into the NGINX container
- name: nginx-proxy-config
  configMap:
    name: nginx-conf
